version: "3.9"
services:
  web:
    build: ./tracker
  #  volumes:
  #   - ./tracker/server:/usr/src/app/server # For Nitro API Testing, without continual builds
    ports:
      - "8100:3000" 
    depends_on:
      - aggregator
      - redis
  aggregator: 
    build: ./aggregators
    links: 
      - redis
    environment:
      - YOUTUBE_API_KEY=AIzaSyAuPkuxKoIu2u6sy312SBXLN_U3WgCmEQM
    volumes:
      - ./aggregators:/usr/src/app
    depends_on:
      - redis
  redis:
    image: "redis:alpine" 